version: "3.8"

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - .:/app 
    environment:
      - PYTHONUNBUFFERED=1 
    restart: unless-stopped

volumes:
  app_data:
